#!/bin/sh
### BEGIN INIT INFO
# Provides:          pod-manager-configuration-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO
#
# Copyright (c) 2015-2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CONFIGURATION_AGENT_SCRIPT="/usr/bin/pod-manager-configuration-agent"

configuration_agent_running() {
    RUNNING_PID=`pgrep -af "${CONFIGURATION_AGENT_SCRIPT}" | cut -d ' ' -f1`
    if [ -z ${RUNNING_PID} ]
    then
        return 0
    else
        return ${RUNNING_PID}
    fi
}

start_configuration_agent() {
    configuration_agent_running
    AGENT_RUNNING_PID=$?
    if [ ${AGENT_RUNNING_PID} -eq 0 ]
    then
        ${CONFIGURATION_AGENT_SCRIPT} &
        echo "Pod Manager Configuration Agent started."
    else
        echo "Pod Manager Configuration Agent is already running."
    fi
}

stop_configuration_agent() {
    configuration_agent_running
    AGENT_RUNNING_PID=$?
    if [ ${AGENT_RUNNING_PID} -ne 0 ]
	then
		kill -9 ${AGENT_RUNNING_PID}
		echo "Pod Manager Configuration Agent stopped."
    else
        echo "Pod Manager Configuration Agent is already stopped."
    fi
}

configuration_agent_status () {
     configuration_agent_running
     AGENT_RUNNING_PID=$?
     if [ ${AGENT_RUNNING_PID} -eq 0 ]
     then
         echo "Pod Manager Configuration Agent is stopped."
     else
         echo "Pod Manager Configuration Agent is running."
     fi
}

case "$1" in
    start)
        start_configuration_agent
        ;;
    stop)
        stop_configuration_agent
        ;;
    restart)
        stop_configuration_agent
        start_configuration_agent
        ;;
    status)
        configuration_agent_status
        ;;
    *)

    echo "Usage: /etc/init.d/pod-manager-configuration-agent {start|stop|restart|status}"
    exit 1
esac

exit 0