#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}

killservice 'Restd';
killservice 'IPMIModule';
killservice 'Memdbd';
killservice 'Assetd';
killservice 'AssetModule'
killservice 'Redfishd';
killservice 'RMMLogd';
killservice 'Registerd'

rm -f /etc/rcS.d/S101rmm
