#!/usr/bin/env bash

#
# Copyright (c) 2018-2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

POSTGRES_PASSWORD=$(kubectl get secret --namespace default podm-db-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
PODM_POSTGRES_USER_PASSWORD=$(kubectl get secret --namespace default pod-manager-secret -o jsonpath="{.data.database-password}" | base64 --decode)

set -x

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

kubectl cp ${SCRIPT_DIR}/../helm/pod-manager/scripts/recreate-all-databases-on-cluster.sh default/podm-db-postgresql-0:/tmp/
kubectl exec -it podm-db-postgresql-0 -- bash -c "export PGPASSWORD=$POSTGRES_PASSWORD; export PODM_POSTGRES_USER_PASSWORD=$PODM_POSTGRES_USER_PASSWORD; /tmp/recreate-all-databases-on-cluster.sh recreate_all_databases_and_user"
kubectl exec -it podm-db-postgresql-0 -- bash -c "rm /tmp/recreate-all-databases-on-cluster.sh"

set +x
set +e
