#!/bin/bash
function killservice()
{   
    pgrep -x $1 > /dev/null 
    if [ $? -eq 0 ]
    then
        killall -9 -q $1 & > /dev/null
    fi
}

killservice 'Restd';
killservice 'IPMIModule';
killservice 'Memdbd';
killservice 'Assetd';
killservice 'AssetModule'
killservice 'Redfishd';
killservice 'RMMLogd';
killservice 'Registerd';
killservice 'snmpd';
killservice 'SNMPSubagentd';

echo "stop all service when uninstall the rmm" > /root/rmm.log

