/**
 * Copyright (c)  2015, Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __LIBUTILS_RMM_JSON_H__
#define __LIBUTILS_RMM_JSON_H__

#define RMM_JSON_ID                     "Id"
#define RMM_JSON_UUID                   "UUID"
#define RMM_JSON_NAME                   "Name"
#define RMM_JSON_HREF                   "Links"
#define RMM_JSON_RACkUUID               "RackUUID"

#define RMM_JSON_POD                    "POD"
#define RMM_JSON_RACK                   "Rack"
#define RMM_JSON_RMC                    "RMC"
#define RMM_JSON_XLOC                   "XLocation"
#define RMM_JSON_ULOC                   "ULocation"
#define RMM_JSON_UHEIGHT                "UHeight"

#define RMM_JSON_LOC                    "Location"
#define RMM_JSON_ZONE_ID                "Zone_id"
#define RMM_JSON_RACK_UNITS             "RackUnits"
#define RMM_JSON_RACK_LOC               "RackLocation"
#define RMM_JSON_PRESENCE               "Presence"
#define RMM_JSON_DESC                   "Description"
#define RMM_JSON_CREATED_DATE           "CreatedDate"
#define RMM_JSON_UPDATED_DATE           "UpdatedDate"
#define RMM_JSON_ASSET_TAG              "AssetTag"
#define RMM_JSON_STATE                  "EnabledState"

#define RMM_JSON_PROPERTY_NAME          "PropertyName"
#define RMM_JSON_ALLOWABLE_VALUES       "AllowableValues"
#define RMM_JSON_CAPABILITIES           "Capabilities"
#define RMM_JSON_AVALIBLE_ACTIONS       "AvailableActions"
#define RMM_JSON_RESET_TYPE             "ResetType"

#define RMM_JSON_RESET                  "Reset"
#define RMM_JSON_RESETED                "Reseted"
#define RMM_JSON_RESET_BIG              "Reset"
#define RMM_JSON_RESETED_BIG            "Reseted"
#define RMM_JSON_DRAWER_RESET           "DrawerReset"

#define RMM_JSON_SETUARTTARGET          "SetUartTarget"
#define RMM_JSON_RESET_MODE_SERVICE     "Service"
#define RMM_JSON_RESET_MODE_RMM         "RMM"
#define RMM_JSON_RESULT                 "Result"
#define RMM_JSON_LOAD_FACTORY_DEFAULT   "LoadFactoryDefault"
#define RMM_JSON_SET_DESIRED_SPEED_PWM  "SetDesiredSpeedPWM"
#define RMM_JSON_DESIRED_SPEED_PWM      "DesiredSpeedPWM"
#define RMM_JSON_DESIRED_SPEED_PWM_VALUES  "DesiredSpeedPWM@AllowableValues"
#define RMM_JSON_DESIRED_SPEED_RPM      "DesiredSpeedRPM"

#define RMM_JSON_RESET_SOFT_STR         "Soft"
#define RMM_JSON_RESET_HARD_STR         "Hard"
#define RMM_JSON_NORMAL_STR             "Normal"
#define RMM_JSON_PRESENT                "Present"

#define RMM_JSON_SERIAL_NUM             "SerialNumber"
#define RMM_JSON_MANUFACTURE            "Manufacturer"
#define RMM_JSON_MODEL_NUM              "Model"
#define RMM_JSON_PART_NUM               "PartNumber"
#define RMM_JSON_FIRMWARE_VER           "FirmwareVersion"
#define RMM_JSON_MODIFY                 "Modified"
#define RMM_JSON_TYPE                   "Type"
#define RMM_JSON_CONTEXT                "Context"

#define RMM_JSON_ACTION                 "Action"
#define RMM_JSON_DEST                   "Destination"
#define RMM_JSON_PROTOCOL               "Protocol"
#define RMM_JSON_PORT                   "Port"

#define RMM_JSON_HW_ADDR                "MBPHWAddress"
#define RMM_JSON_IP_ADDR                "MBPIPAddress"
#define RMM_JSON_FRU_INFO               "FRUInfo"
#define RMM_JSON_FRU_RESULT             "Result"
#define RMM_JSON_REQ_ENABLED_STATE      "RequestEnabledState"
#define RMM_JSON_API_VER                "ApiVersion"
#define RMM_JSON_PLATFORM               "Platform"

#define RMM_JSON_ODATA_ID               "@odata.id"
#define RMM_JSON_ODATA_TYPE             "@odata.type"
#define RMM_JSON_ODATA_CONTEXT          "@odata.context"
#define RMM_JSON_RF_COPY_RIGHT          "@Redfish.Copyright"
#define RMM_JSON_MEMBERS_ODATA_COUNT    "Members@odata.count"
#define RMM_JSON_MANAGEDBY_ODATA_COUNT  "ManagedBy@odata.count"
#define RMM_JSON_CONTAINS_ODATA_COUNT   "Contains@odata.count"
#define RMM_JSON_MANAGERFORCHASSIS_ODATA_COUNT  "ManagerForChassis@odata.count"
#define RMM_JSON_MANAGERFORMBP_ODATA_COUNT      "ManagerForMBP@odata.count"

#define RMM_JSON_RF_ID                  "Id"
#define RMM_JSON_RF_NAME                "Name"
#define RMM_JSON_RF_CONTEXT             "Context"
#define RMM_JSON_RF_PROTOCOL            "Protocol"
#define RMM_JSON_RF_STATUS              "Status"
#define RMM_JSON_RF_STATUS_STATE        "State"
#define RMM_JSON_RF_STATUS_HEALTH       "Health"
#define RMM_JSON_RF_SERVICE_ENABLED     "ServiceEnabled"
#define RMM_JSON_RF_DELIVERY_RETRY      "DeliveryRetryAttempts"
#define RMM_JSON_RF_DELIVERY_RETRY_INTERVAL "DeliveryRetryIntervalInSeconds"

/*Chassis*/
#define RMM_JSON_CHASSIS                "Chassis"
#define RMM_JSON_CHASSISTYPE            "ChassisType"
#define RMM_JSON_OEM                    "Oem"
#define RMM_JSON_RSA                    "RackScale"
#define RMM_JSON_MEMBER_ID              "MemberId"

/*log*/
#define RMM_JSON_COUNT                  "Count"
#define RMM_JSON_LEN                    "Length"
#define RMM_JSON_LOG_INFO               "Loginfo"

/*RACK*/
#define RMM_JSON_RACK_ID                "Rack_id"
#define RMM_JSON_POD_DCUID              "PODDCUID"
#define RMM_JSON_RACK_PUID              "RackPUID"
#define RMM_JSON_PODM_ADDR              "PODMAddress"
#define RMM_JSON_GEO_TAG                "GeoTag"
#define RMM_JSON_RACK_DCUID             "RackDCUID"
#define RMM_JSON_DRAWER_PRESENCE        "DrawerPresence"
#define RMM_JSON_MBP_PRESENCE           "MBPPresence"
#define RMM_JSON_DISAGGR                "RackSupportsDisaggregatedPowerCooling"
#define RMM_JSON_COMPONENT_TYPE         "ComponentType"
#define RMM_JSON_IMAGE                  "Image"
#define RMM_JSON_MAGAGEDBY              "ManagedBy"
#define RMM_JSON_MAGAGER_FOR_CHASSIS    "ManagerForChassis"
#define RMM_JSON_MAGAGER_FOR_MBP        "ManagerForMBP"
#define RMM_JSON_CONTAINS               "Contains"

/*DRAWER*/
#define RMM_JSON_DRAWERS                "Drawers"
#define RMM_JSON_DRAWER_COLL            "Drawers"
#define RMM_JSON_DRAWER_ID              "Drawer_id"
#define RMM_JSON_DRAWER_IPADDRESS       "DrawerIPAddress"
#define RMM_JSON_DRAWER_RUID            "DrawerRUID"
#define RMM_JSON_DRAWER_PUID            "DrawerPUID"

#define RMM_JSON_DRAWER_STATE             "ThermalState"
#define RMM_JSON_DRAWER_POWER_CONSUME     "PowerConsumedWatt"
#define RMM_JSON_DRAWER_PRESENT_TEMP      "PresentTemperatureCelsius"
#define RMM_JSON_DRAWER_POWER_AND_THERMAL "PowerAndThermal"
#define RMM_JSON_MAX_DRAWER_SUPPORTED     "MaxDrawerSupported"
#define RMM_JSON_CONTAINEDBY              "ContainedBy"

/*Power Zone*/
#define RMM_JSON_POWER_ZONES            "PowerZones"
#define RMM_JSON_POWER_ZONE_COLL        "PowerZones"
#define RMM_JSON_POWER_ZONE_NAME        "Name"
#define RMM_JSON_PSU_NAME               "Name"
#define RMM_JSON_PZONE_ID               "Powerzone_id"
#define RMM_JSON_PSU_ID                 "Psu_id"
#define RMM_JSON_POWER_INPUT            "PresentPowerInputWatt"
#define RMM_JSON_POWER_OUTPUT           "PowerOutputWatts"
#define RMM_JSON_POWER_MAX_RATED_CAP    "MaxRatedPowerCapacityWatt"
#define RMM_JSON_MAX_PSUS_SUPPORT       "MaxPSUsSupported"
#define RMM_JSON_PSU_NUMBER_OF_PRESENT  "NumberOfPSUsPresent"
#define RMM_JSON_PSUS                   "Psus"
#define RMM_JSON_REDUNDANCY_SET         "RedundancySet"
#define RMM_JSON_HEALTH_CODE            "Health"
#define RMM_JSON_STATUS                 "Status"
#define RMM_JSON_HEALTH_STATUS          "Status"
#define RMM_JSON_PSU_ENABLE_STATE       "State"
#define RMM_JSON_POWER_CONSUMED         "PowerConsumedWatts"
#define RMM_JSON_POWER_CAP              "PowerCapacityWatts"
#define RMM_JSON_LAST_POWER_OUTPUT      "LastPowerOutputWatts"
#define RMM_JSON_MAX_POWER_CAP          "2528"
#define RMM_JSON_POWERSUPPLIES          "PowerSupplies"

/*thermalzones*/
#define RMM_JSON_TZONE_NAME             "Name"
#define RMM_JSON_TZONE_ID               "Thermalzone_id"
#define RMM_JSON_FAN_NAME               "Name"
#define RMM_JSON_FAN_ID                 "Fan_id"
#define RMM_JSON_THERMAL_ZONES          "ThermalZones"
#define RMM_JSON_THERMAL_ZONE_COLL      "ThermalZones"
#define RMM_JSON_PRESENT_TEMP           "PresentTemperatureCelsius"
#define RMM_JSON_READING_CELSIUS		"ReadingCelsius"
#define RMM_JSON_PHYSICAL_CONTEXT		"PhysicalContext"
#define RMM_JSON_RELATED_ITEM			"RelatedItem"
#define RMM_JSON_OUT_LET_TEMP           "OutletTemperatureCelsius"
#define RMM_JSON_AIRFLOW                "VolumetricAirflow"
#define RMM_JSON_MAX_FANS_SUPPORTED     "MaxFansSupported"
#define RMM_JSON_NUM_OF_FANS_PRESENT    "NumberOfFansPresent"
#define RMM_JSON_FANS                   "Fans"
#define RMM_JSON_TEMPERATURES           "Temperatures"
#define RMM_JSON_ENABLE_STATE           "EnabledState"
#define RMM_JSON_FAN_ENABLE_STATE       "State"
#define RMM_JSON_HEALTH_STATE           "Status"
#define RMM_JSON_TACHOMETER_READING     "ReadingRPM"
#define RMM_JSON_LOWER_NON_CRITICAL     "LowerNonCritical"
#define RMM_JSON_UPPER_NON_CRITICAL     "UpperNonCritical"
#define RMM_JSON_LOWER_CRITICAL         "LowerCritical"
#define RMM_JSON_UPPER_CRITICAL         "UpperCritical"
#define RMM_JSON_THRESHOLD              "TachMeterThreshold"
#define RMM_JSON_SPEED_UNIT             "SpeedUnit"
#define RMM_JSON_UNIT_TYPE              "UnitType"
#define RMM_JSON_REQ_STATE_CHANGE       "RequestStateChange"
#define RMM_JSON_SET_DESIRED_SPEED      "SetDesiredSpeedPWM"
#define RMM_JSON_DESIRED_VALUE          "DesiredValue"
#define RMM_JSON_RPM                    "RPM"
#define RMM_JSON_PWM                    "DesiredSpeedPWM"

/*MZone*/
#define RMM_JSON_MBPS                   "MBPs"
#define RMM_JSON_MBP_COLL               "MBPCollection"
#define RMM_JSON_MBP_ID                 "Mbp_id"
#define RMM_JSON_FW_STATE               "FirmwareState"
#define RMM_JSON_TARGET_TRAY            "TargetTray"
#define RMM_JSON_TARGET_INDEX           "TargetIndex"
#define RMM_JSON_TARGET_COMPONET        "TargetComponent"

#define RMM_JSON_UPDATING               "Updating"
#define RMM_JSON_UPDATE                 "Update"
#define RMM_JSON_UPDATE_BIG             "Update"
#define RMM_JSON_UPDATED                "Updated"
#define RMM_JSON_UPDATED_BIG            "Updated"
#define RMM_JSON_UPDATE_FAIL            "Failed"

/*Redfish*/
#define RMM_JSON_RF_EVENT_SERVICE       "EventService"
#define RMM_JSON_RF_SUPPORTED_EVT_TYPES "EventTypesForSubscription"
#define RMM_JSON_RF_EVT_TYPES           "EventTypes"
#define RMM_JSON_RF_EVT                 "Event"
#define RMM_JSON_RF_NAME                "Name"
#define RMM_JSON_RF_DESC                "Description"
#define RMM_JSON_RF_LISTENER            "Listener"
#define RMM_JSON_RF_DEST_URL            "Destination"
#define RMM_JSON_RF_MEMBER              "Member"
#define RMM_JSON_RF_SELF                "Self"
#define RMM_JSON_RF_SUBSCRIPTION        "Subscriptions"
#define RMM_JSON_RF_LINKS               "Links"
#define RMM_JSON_SUBSCRIPTION           "Subscribe"
#define RMM_JSON_UNSUBSCRIPTION         "Unsubscribe"
#define RMM_JSON_NODE_ADDED             "NodeAdded"
#define RMM_JSON_NODE_REMOVED           "NodeRemoved"
#define RMM_JSON_HOST_STATE             "HostState"
#define RMM_JSON_ZONE                   "Zone"
#define RMM_JSON_TRAY                   "Tray"
#define RMM_JSON_NODE                   "Node"
#define RMM_JSON_HEIGHT                 "Height"
#define RMM_JSON_WIDTH                  "Width"
#define RMM_JSON_HOST_STATE_ON          "HostStateOn"
#define RMM_JSON_HOST_STATE_OFF         "HostStateOff"
#define RMM_JSON_MSG_ID                 "MessageId"
#define RMM_JSON_MSG_ARGS               "MessageArgs"
#define RMM_JSON_MSG_EVENTS             "Events"
#define RMM_JSON_MSG_CONTEXT            "Context"
#define RMM_JSON_MSG_ORIGIN             "OriginOfCondition"

#define RMM_JSON_MSG_EVT_TYPE           "EventType"
#define RMM_JSON_MEMBERS_COUNT          "Members@odata.count"
#define RMM_JSON_MANAGER_RESET          "#Manager.Reset"
#define RMM_JSON_MANAGER_TYPE           "ManagerType"
#define RMM_JSON_MODEL                  "Model"

#define RMM_JSON_TARGET                 "target"
//#define RMM_JSON_ID                   "Id"
#define RMM_JSON_REDFISH_VERSION        "RedfishVersion"
#define RMM_JSON_SERVICE_ENTRY_POINT_UUID    "ServiceEntryPointUUID"
#define RMM_JSON_FIRMWARE_VERSION            "FirmwareVersion"
#define RMM_JSON_DATETIME                    "DateTime"
#define RMM_JSON_DATETIME_LOCAL_OFFSET       "DateTimeLocalOffset"
#define RMM_JSON_POST_ACTIONS                "Actions"

#define RMM_JSON_ODATA_TYPE_CHASSIS_COLL    "ChassisCollection"
#define RMM_JSON_ODATA_TYPE_SVR_ROOT        "ServiceRoot"
#define RMM_JSON_ODATA_TYPE_MGR_COLL        "ManagerCollection"
#define RMM_JSON_ODATA_TYPE_MGR             "Manager"
#define RMM_JSON_ODATA_TYPE_RACK            "RackChassis"
#define RMM_JSON_ODATA_TYPE_CHASSIS         "Chassis"
#define RMM_JSON_ODATA_TYPE_TZONE_COLL      "ThermalZoneCollection"
#define RMM_JSON_ODATA_TYPE_TZONE           "ThermalZone"
#define RMM_JSON_ODATA_TYPE_FAN_COLL        "FanCollection"
#define RMM_JSON_ODATA_TYPE_FAN             "Fan"
#define RMM_JSON_ODATA_TYPE_MBP_COLL        "MBPCollection"
#define RMM_JSON_ODATA_TYPE_MBP             "MBP"
#define RMM_JSON_ODATA_TYPE_DRAWER_COLL     "DrawerCollection"
#define RMM_JSON_ODATA_TYPE_DRAWER          "DrawerChassis"
#define RMM_JSON_ODATA_TYPE_PZONE_COLL      "PowerZoneCollection"
#define RMM_JSON_ODATA_TYPE_PZONE           "PowerZone"
#define RMM_JSON_ODATA_TYPE_PSU_COLL        "PSUCollection"
#define RMM_JSON_ODATA_TYPE_PSU             "PowerSupplyUnit"

#define UPGRADE_FILE_SIGNED                 "/tmp/rmm_upgrade.signed"
#define UPGRADE_FILE_TARBALL                "/tmp/rmm_upgrade.tar.gz"
#define UPGRADE_DEB_FILE                    "rmm-base"

#define RMM_JSON_MEMBERS              "Members"
#define RMM_JSON_STATE_ENABLED        "Enabled"
#define RMM_JSON_STATE_DISABLED       "Disabled"
#define RMM_JSON_STATE_NOT_APP        "Not_app"
#define RMM_JSON_STATE_OFFLINE        "Offline"
#define RMM_JSON_PROTOCOL_ENABLED     "ProtocolEnabled"

#define RMM_JSON_RACK_UNITS_OU        "OU"
#define RMM_JSON_RACK_UNITS_RU        "RU"

#define RMM_JSON_HEALTH_CODE_UNKNOW      1
#define RMM_JSON_HEALTH_CODE_HEALTH      5
#define RMM_JSON_HEALTH_CODE_WARNING     3
#define RMM_JSON_HEALTH_CODE_CRITICAL    4
#define RMM_JSON_HEALTH_MASK             0x404
#define RMM_JSON_HEALTH_CODE_CLEAR       0


#define RMM_JSON_HEALTH_CODE_UNKNOW_STR     "Unknow"
#define RMM_JSON_HEALTH_CODE_HEALTH_STR     "OK"
#define RMM_JSON_HEALTH_CODE_WARNING_STR    "Warning"
#define RMM_JSON_HEALTH_CODE_CRITICAL_STR   "Critical"

/* manager */
#define RMM_JSON_MANAGER_NETWORK_PROTOCOL   "NetworkProtocol"
#define RMM_JSON_MANAGER_ETH_INTERFACES     "EthernetInterfaces"
#define RMM_JSON_MANAGER_STATE              "State"
#define RMM_JSON_MANAGER_HEALTH             "Health"
#define RMM_JSON_MANAGER_NETWORK_HOSTNAME   "HostName"
#define RMM_JSON_MANAGER_NETWORK_FQDN       "FQDN"
#define RMM_JSON_MANAGER_NETWORK_HTTP       "HTTP"
#define RMM_JSON_MANAGER_NETWORK_HTTPS      "HTTPS"
#define RMM_JSON_MANAGER_NETWORK_SSH        "SSH"
#define RMM_JSON_MANAGER_FACTORY_MAC        "PermanentMACAddress"
#define RMM_JSON_MANAGER_MAC                "MACAddress"
#define RMM_JSON_MANAGER_LINK_TECH          "LinkTechnology"
#define RMM_JSON_MANAGER_SPD_MBPS           "SpeedMbps"
#define RMM_JSON_MANAGER_AUTO_SENSE         "AutoNeg"
#define RMM_JSON_MANAGER_FULL_DUPLEX        "FullDuplex"
#define RMM_JSON_MANAGER_FRAME_SIZE         "MTUSize"
#define RMM_JSON_MANAGER_MAX_IPV6_ADDR      "MaxIPv6StaticAddresses"

#define RMM_JSON_MANAGER_VLAN_ENABLE        "VLANEnable"
#define RMM_JSON_MANAGER_VLAN_ID            "VLANId"
#define RMM_JSON_MANAGER_VLAN_TAGGED        "Tagged"
#define RMM_JSON_MANAGER_IP_ADDR            "Address"
#define RMM_JSON_MANAGER_SUBNET_MASK        "SubnetMask"
#define RMM_JSON_MANAGER_ADDR_ORIGIN        "AddressOrigin"
#define RMM_JSON_MANAGER_IPV4_GATEWAY       "Gateway"
#define RMM_JSON_MANAGER_IPV4_ADDR          "IPv4Addresses"
#define RMM_JSON_MANAGER_IPV6_PREFIX        "Prefix"
#define RMM_JSON_MANAGER_IPV6_PRECEDENCE    "Precedence"
#define RMM_JSON_MANAGER_IPV6_LABEL         "Label"
#define RMM_JSON_MANAGER_IPV6_POLICY        "IPv6AddressPolicyTable"
#define RMM_JSON_MANAGER_IPV6_PREFIX_LEN    "PrefixLength"
#define RMM_JSON_MANAGER_IPV6_ADDR_STATE    "AddressState"
#define RMM_JSON_MANAGER_IPV6_STATIC        "IPv6StaticAddresses"
#define RMM_JSON_MANAGER_IPV6_ADDR          "IPv6Addresses"
#define RMM_JSON_MANAGER_IPV6_GATEWAY       "IPv6DefaultGateway"
#define RMM_JSON_MANAGER_NAME_SERVERS       "NameServers"
#define RMM_JSON_MANAGER_VLANS              "VLANs"

#define RMM_JSON_OEM_RSA                    "RackScale"
#define RMM_JSON_OEM_INTEL_RSA              "Intel:RackScale"
#define RMM_JSON_OEM_POST_ACTIONS           "Actions/Oem"

#endif
