#!/usr/bin/env bash

# Copyright (c) 2015-2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

USER_NAME="podm"

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi

DB_PASSWORD=nodecomposer

set -e

sudo service postgresql start
echo "Killing remaining connections do database..."
sudo -u postgres psql -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'nodecomposer' AND pid <> pg_backend_pid()"
sudo -u postgres dropdb --if-exists nodecomposer
sudo -u postgres dropuser --if-exists nodecomposer
sudo -u postgres psql -c "CREATE USER nodecomposer WITH SUPERUSER PASSWORD '${DB_PASSWORD}'"
sudo -u postgres createdb nodecomposer
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE nodecomposer to nodecomposer"

echo "Node Composer database cleared - schema will be recreated during next application startup."

set +e
