#!/bin/bash
# By Jack Zark Yinger
res=$(ipmitool -I lanplus -H 1.1.1.1 -U admin -P admin raw 0x38 0x02>&1)
res=$(perl -le 'print hex(@ARGV[0])' $res)
for i in {0,2,4,6}; do
	if (( $res&(1<<$i) )); then
		echo -e "Tray$(($i/2+1)) is present +"
	else
		echo -e "Tray$(($i/2+1)) is absent  o"
	fi
done 
res=$(ipmitool -I lanplus -H 1.1.1.2 -U admin -P admin raw 0x38 0x02>&1)
res=$(perl -le 'print hex(@ARGV[0])' $res)
for i in {0,2,4,6}; do
	if (( $res&(1<<$i) )); then
		echo -e "Tray$(($i/2+5)) is present +"
	else
		echo -e "Tray$(($i/2+5)) is absent  o"
	fi
done 
